site_name: Dracon
site_description: A modular configuration system and CLI generator for Python
repo_url: https://github.com/jdisset/dracon
repo_name: jdisset/dracon

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - "Introduction": "index.md"
  - "Core Concepts":
      - "Loading Configuration": "loading.md"
      - "Includes (Modularity)": "includes.md"
      - "Interpolation (Dynamic Values)": "interpolation.md"
      - "Merging Configurations": "merging.md"
      - "Instructions (Composition Logic)": "instructions.md"
      - "Working with Types": "types.md"
  - "Advanced Features":
      - "Deferred Nodes": "deferred.md"
      - "Resolvable Values": "resolvable.md"
      - "KeyPaths": "keypaths.md"
  - "Command-Line Interfaces": "cli.md"
  # - 'API Reference': 'api.md'
  # - 'Recipes': 'recipes.md'
