default_settings: 
  setting1: default_value1
  setting2: default_value2
  setting_list:
    - item1
    - item2
    - item3
  <<: !include file:$DIR/../params
  again: *pkg:dracon:tests/configs/params
  just_simple: *pkg:dracon:tests/configs/params@simple_params.additional_settings

fstem: !include file:$DIR/../fstem

ppath: *env:TESTVAR2

