default_settings: 
  setting1: default_value1
  setting2: default_value2
  setting_list:
    - item1
    - item2
    - item3
  <<: *pkg:dracon:tests/configs/params
  again: *pkg:dracon:tests/configs/params
  just_simple: *file:$DIR/params@simple_params.additional_settings


ppath: *env:TESTVAR2

empty: *pkg:dracon:tests/configs/empty

scalar: !include file:$DIR/scalar
